name: lint/test/typeCheck, then deploy if on main
env: 
  NODE_VERSION: '14.x'
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
on: [push]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run lint --if-present
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm test --if-present
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run typeCheck --if-present

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    needs: [lint, typeCheck, test]
    name: Upload to Amazon S3 Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci 
      - run: npm run build:staging
      - name: Copy files to staging bucket
        run: aws s3 sync ./dist/ s3://staging.simularium.allencell.org --delete
      - name: Clear cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CFE_CLOUDFRONT_DISTRIBUTION_ID_STAGING }} --paths "/*"

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [lint, typeCheck, test]
    name: Upload to Amazon S3 Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci 
      - run: npm run build
      - name: Copy files to production bucket
        run: aws s3 sync ./dist/ s3://production.simularium.allencell.org --delete
      - name: Clear cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CFE_CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }} --paths "/*"
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#simularium-dev'
        if: always()
